# this file uses prebuilt image in dockerhub
services:
  jekyll:
    #image: amirpourmand/al-folio:slim
    build: .
    platform: linux/arm64/v8
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
