name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Update _config.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "_config.yml"
          changes: |
            {
              "giscus.repo": "${{ github.repository }}",
              "baseurl": ""
            }

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          pip3 install --upgrade jupyter

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build site
        run: |
          export JEKYLL_ENV=production
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"

      - name: Purge unused CSS
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4